name: Go

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  build-test:
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
          
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Install make
      run: sudo apt-get install build-essential

    - name: Build
      run: make build

    - name: Test
      env:
        API_KEY: ${{ secrets.API_KEY }}
        MAINTENANCE_CONNECTION_STRING: ${{ secrets.MAINTENANCE_CONNECTION_STRING }}
        TEST_CONNECTION_STRING: ${{ secrets.TEST_CONNECTION_STRING }}
        WORKING_CONNECTION_STRING: ${{ secrets.WORKING_CONNECTION_STRING }}
        DATABASE_NAME: ${{secrets.DATABASE_NAME}}
      run: make test
